### ISSUE TITLE
Issue with fullscreen on Linux

### ISSUE THREAD

**Issue by Leebre** [stohrendorf/CroftEngine#259]
I am getting an issue with the fullscreen mode not working properly in Linux. When I switch to fullscreen, I still see the top/bottom panels of my desktop environment. I am using the Mate DE in an Arch variant on an x86 desktop PC. See the screenshot below:

![Fullscreen_issue](https://user-images.githubusercontent.com/49341316/184535752-6af389ab-52cd-44bf-99bc-a8efc8605209.png)

**Comment by stohrendorf** [comment]
I haven't tested Linux for quite a while now, sadly. Will look into this when I'm back from vacation.

**Comment by Leebre** [comment]
> I haven't tested Linux for quite a while now, sadly. Will look into this when I'm back from vacation.

Ok, thanks!
