### ISSUE TITLE
Add Python3 to the list of build dependencies

### ISSUE THREAD

**Issue by carlo-bramini** [stohrendorf/CroftEngine#275]
README.md lists several build dependencies (boost, libpng, etc...).
Perhaps, Python3 needs to be added to this list.

**Comment by stohrendorf** [comment]
Indeed, thanks for the hint.

**Comment by carlo-bramini** [comment]
> Indeed, thanks for the hint.

I'm wondering if you could update the build instruction with Python and vcpkg, because I'm trying to compile with MSVC and after some tests I'm still getting `"Python 3 Library not found"` from CMake. Installing also the official 3.10.7 binaries of python and adding the tool to the path didn't solve the trouble.
Thank you.

**Comment by stohrendorf** [comment]
That will be part of the instructions. In your case, what you need is something like `-DPython3_ROOT=E:\Python38` when calling cmake.
