### ISSUE TITLE
Adding support for playing demo version.

### ISSUE THREAD

**Issue by carlo-bramini** [stohrendorf/CroftEngine#278]
It would be worth to make possible to run the demo version of the game.
The demo, which can be downloaded freely, provides just these files into the DATA directory:

```
INSTALL.PCX
LEVEL2.PHD
TITLE.PHD
TITLEH.PCX
```

So, I'm wondering if it is possible to test this level in some way.
I tried to add a `tr1demo` directory into `share\croftengine\gameflows` with some modified files, but I could not make it working.
Thank you very much.

**Comment by stohrendorf** [comment]
The demo version contains (as far as I remember) a different level data format. This was never tested with this engine, so it's probably "just" some issue with the level data reading.

**Comment by stohrendorf** [comment]
I checked the code, and unfortunately there's no proper detection of demo levels, and it tries to load the levels as regular release levels. This can be fixed, though, but I'm not sure it's worth the effort.

**Comment by carlo-bramini** [comment]
> I checked the code, and unfortunately there's no proper detection of demo levels, and it tries to load the levels as regular release levels. This can be fixed, though, but I'm not sure it's worth the effort.

Thank you very much for support.
Actually, I understand that's not an high priority task and this issue could be left open for the future.
If I can write my opinion, supporting the demo levels will allow people (like me) who has not (yet) access to the full game to see this reimplementation of the engine in action.

I hope that its support may be included one day.

**Comment by stohrendorf** [comment]
Now in master.
