### ISSUE TITLE
Toggle For Classic-Style Lighting?

### ISSUE THREAD

**Issue by OpenRift412** [stohrendorf/CroftEngine#281]
I noticed that even with all the fancy settings disabled, the lighting still appears different compared to either vanilla or TombATI (Lara still has self-shadowing on her model, for instance). Would it be possible to have the option to use the original lighting?

**Comment by stohrendorf** [comment]
It's not the target of this engine to really replicate the original game to its full extent. Its goal is to modernize the graphics and make it somewhat distinct, taking advantage of the hardware improvements of the last 25 years and the massive increase in resolution. If you want the original visuals, just use the original game, maybe with some patches to increase resolution.

**Comment by stohrendorf** [comment]
@OpenRift412 are you satisfied with this answer, or do you have more concerns about this? If not, I'd like to close this issue.

**Comment by OpenRift412** [comment]
> @OpenRift412 are you satisfied with this answer, or do you have more concerns about this? If not, I'd like to close this issue.

I suppose so, feel free to close it.

**Comment by stohrendorf** [comment]
Thank you. I'm sorry this doesn't meet your expectations.
