### ISSUE TITLE
Separate Key/Gamepad Binds for Menus

### ISSUE THREAD

**Issue by OpenRift412** [stohrendorf/CroftEngine#282]
Just a word of advice, I would suggest having the menus use separate binds that are **not** entirely dependent on the in-game key/gamepad binds, that way navigation can be more intuitive.

My suggestion would be the following:

**Keyboard**

Basic Navigation: **Arrow Keys/WASD**
Select: **Enter/Space**
Back: **Esc**
Next Menu: **E**
Previous Menu: **Q**

**Gamepad**

Basic Navigation: **Left Stick/D-Pad** (would also be nice if you could use both for movement in-game as well without having to switch the binds)
Select: **A Button (X on Playstation)**
Back: **B Button (Circle on Playstation)**
Next Menu: **Right Bumper (R1 on Playstation)**
Previous Menu: **Left Bumper (L1 on Playstation)**

**Comment by stohrendorf** [comment]
Thank your the report. This will eventually be implemented some time in the future.

**Comment by stohrendorf** [comment]
Implemented.
