### ISSUE TITLE
I can´t see logos/text

### ISSUE THREAD

**Issue by Redline1991** [stohrendorf/CroftEngine#283]
Good morning. It turns out that yesterday I installed version 1.12, I have also tried with 1.11 and the same thing happens, that after the videos, I get to the main menu and it turns out that I only see the wallpaper but I don't see any logos or text and I can't start play. I have tried both with TR1 and with sabatu's. Can you help me? Thanks.
![001256](https://user-images.githubusercontent.com/118980840/203779629-a2d94ebe-4afe-4e99-af88-050ccedf0cea.jpg)

**Comment by stohrendorf** [comment]
Please make sure you're running on a non-intel graphics card. You can check this in your log files.
1. In the launcher "Configuration" tab, select "Show Data Location".
2. In that folder, look for files named like `croftengine.12345.log`, and open the one with the highest number.
3. Look for lines containing `OpenGL vendor` and `OpenGL renderer` and ensure it's _not_ intel.
4. If it's intel (which I currently suspect), open nVidia control panel and manually set it to use the dedicated graphics adapter. I'm not sure how to do that with AMD.

**Comment by Redline1991** [comment]
Hi! No, I have the amd RX 570 4gb, and of course with TOMBATI it works correctly, even with the hd textures, but not here, I'm even looking for the file you mentioned and I can't find it anywhere. Thanks.

**Comment by stohrendorf** [comment]
Look for files like these. Send one of those with the biggest number that has a size larger than (roughly) 3 KB.
![grafik](https://user-images.githubusercontent.com/7853507/203940816-9db5470e-491e-4b14-ba1b-34531c52e6bf.png)

**Comment by Redline1991** [comment]
Ok, I just found it but I had to install the program again since neither "rendered" nor "vendor" appeared. I am attaching the file that only came out to me.
[croftengine.log](https://github.com/stohrendorf/CroftEngine/files/10092285/croftengine.log)

**Comment by stohrendorf** [comment]
Was the driver installed through windows update? If so, download it manually from the AMD website and install that. Windows update versions tend to simply not work.

**Comment by Redline1991** [comment]
Nop. Always i install the drivers from amd web and always clean install. I dont like windows update so much 😂

**Comment by stohrendorf** [comment]
Please send the most recent crash dump in the "crashdumps" folder.

**Comment by Redline1991** [comment]
The "Crashdumps" folder is empty. That folder doesn´t have any file.

**Comment by stohrendorf** [comment]
I don't know what's happening here, the log doesn't contain anything that looks wrong. The last thing that could be an issue is if you're using the "optional" driver update version, because these are often unstable. Other than that, there's nothing more I can think of.

**Comment by Redline1991** [comment]
I don't know, I only download those found through the app, since checking the page there are others that have not been updated since May. I currently have 22.11.1, which is the latest.// Trying with the xbox controller, it gets into the game but when it starts it stays as if the game were blurry and the screen freezes and there is a black screen.

**Comment by stohrendorf** [comment]
The latest stable version is 22.5.1 from end of april this year. You're using the "optional" version, which is in fact 22.11.1 - "optional" is AMDs word for "beta". In the "System" tab in your settings, change the dropdown right under the update check from "recommended + optional" to "just recommended" (might be different for you, I have to translate this right now). Last time I used the "optional" version the engine didn't run at all.

![grafik](https://user-images.githubusercontent.com/7853507/204082714-bd4d8f41-12ee-4ce6-8d28-454e2521205c.png)

**Comment by Redline1991** [comment]
Yes, I am using the optional one, because if I only leave the one that is from the month of April, the games do not work correctly for me, verified because for other games I also had to leave the "stable" ones for a while for some work. And can't that be solved somehow so that they are compatible for these versions? Since, unlike Nvidia, I suppose that the ones that come out every month are stable, unlike Amd's, so there would have to be some kind of compatibility with this engine with the "beta" versions of Amd.

**Comment by stohrendorf** [comment]
It's an internal issue with the driver. As far as I know, AMD is heavily reworking some internal driver stuff, and the first sign of that was when the engine didn't start at all. As it's an internal issue within the driver itself, and the driver doesn't report any errors to the engine, I can't do anything about that because I don't know what's causing it.

**Comment by Aicop** [comment]
Wanted to add I had the same issue, as mentioned reverting to the latest recommended driver (22.5.1) fixes it.

**Comment by stohrendorf** [comment]
@Redline1991 do you have any more questions or issues with this? Otherwise, I'd like to close this issue if there's nothing else to the problem.
