### ISSUE TITLE
Frame Freezing on Main Menu

### ISSUE THREAD

**Issue by Ax209** [stohrendorf/CroftEngine#285]
Hi there. Trying out the game but I can't seem to get the main menu to run past the first frame. The items (glasses, passport etc) all stay in the centre. The game runs, I can use the controller to get the the first level, but the screen never shows anything other than the first frame of the main menu. 

Let me know if there's anything I can do to try and help out. I'm running an AMD 3800X and a 6900XT GPU. Windows 11. :)

**Comment by stohrendorf** [comment]
Send a log file. Show data location->look for files named something like `croftengine.123.log`, select one with the biggest number that's larger than about 3KB.

**Comment by Ax209** [comment]
[croftengine_20221125_095247.zip](https://github.com/stohrendorf/CroftEngine/files/10091707/croftengine_20221125_095247.zip)

Thanks for getting back to me. 

I had a look around, I believe these are what you need? 

Let me know if you need anything else from me :)

**Comment by stohrendorf** [comment]
Unfortunately, that's an internal driver crash. The only thing that comes to my mind is that you could be using the PRO driver (AMD driver logo is blue instead of red in catalyst control center). In that case, it won't work. Also, if your driver was installed through windows update, try a manual install. The windows update version usually doesn't work for me.

**Comment by Ax209** [comment]
Woah! How did you know all of that?

So yeah, the other day, a windows update did change my red AMD logo to blue! I thought nothing of it. I don't understand why it would do that on its own, I usually install GPU drivers myself. 

Thanks for that. Will go try it now!

**Comment by Ax209** [comment]
Works a treat my friend! Thank you so much for the mod, and also helping me out! You're incredible!

**Comment by tfuGhost** [comment]
I have been suffering from the same issue as described. The logs and crash dumps have the same errors. I tried updating my drivers as the other person did to see if it fixes the problem, but it hasn't. I don't know if responding to this or creating a brand new issue was the right path. But I considered how it was the identical problem, I should respond here. Even if the issue has been closed.

I have both an AMD 2600 and a RX 5500 XT. Windows 10. I can provide my logs and dumps if that helps. The only difference that I have been able to see, if that I see about half a second of animation before it freezes. The circle of items almost get into place before everything freezes.

**Comment by stohrendorf** [comment]
Please open a new issue for that.
