### ISSUE TITLE
License Clarificaiton

### ISSUE THREAD

**Issue by InklingGirl** [stohrendorf/CroftEngine#289]
May we please get some clarification for what this project is licensed under? Thank you.

**Comment by stohrendorf** [comment]
It's licensed under LGPL-3, but parts of it have different licenses for assets or integrated 3rd party code.

**Comment by stohrendorf** [comment]
Did this answer your question?

**Comment by InklingGirl** [comment]
>different licenses for assets or integrated 3rd party code

What are these licenses @stohrendorf?

**Comment by stohrendorf** [comment]
The full list of included licenses and of direct dependency licenses is available at https://app.fossa.com/projects/git%2Bgithub.com%2Fstohrendorf%2FCroftEngine/refs/branch/master/c3db24519fd1e9a161fd3888a2e6c41d6795c523/browse/licenses.

**Comment by InklingGirl** [comment]
Thanks!
