### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by RahRah80** [stohrendorf/CroftEngine#293]
Hello.

How to compile on Linux?

**Comment by stohrendorf** [comment]
```
git checkout https://github.com/stohrendorf/CroftEngine.git
cd CroftEngine
git submodule update --init --recursive
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make
```

**Comment by RahRah80** [comment]
Hello

The first comand didn't work:

error: pathspec 'https://github.com/stohrendorf/CroftEngine.git' did not
match any file(s) known to git

The cmake didn't complete:

-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- GCC or Clang detected
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so
-- Downloading
https://github.com/g-truc/glm/archive/refs/tags/0.9.9.8.tar.gz...
-- Extracting glm-0.9.9.8.tar.gz...
CMake Error at
/usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165
(message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR system log log_setup
  locale)
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458
(_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.18/Modules/FindBoost.cmake:2177
(find_package_handle_standard_args)
  cmake/get_boost.cmake:10 (find_package)
  CMakeLists.txt:55 (include)

**Comment by RahRah80** [comment]
Ok.
That works just fine ;)
