### ISSUE TITLE
Walk-Run glitch on ledge

### ISSUE THREAD

**Issue by ANoDE85** [stohrendorf/CroftEngine#301]
CroftEngine Version: 2.0 (Windows 64bit binary, github release binary)
Levelset: Sabatu's Tomb Raider 1 (10 Jul 2022)
Issue Type: Movement Glitch
Reproducible: Yes

Observed behavior: When running towards certain edges and pressing the WALK button right before the edge, Lara is teleported to the ground below.

Expected behavior: Lara should either enter WALK state and stop at the edge (if WALK was pressed early enough) or run off the edge (if WALK was pressed too late).

Attachments: Savegame

Video: https://youtu.be/NzHyzJqjgqs

[tr1sabatu.zip](https://github.com/stohrendorf/CroftEngine/files/10944854/tr1sabatu.zip)

**Comment by stohrendorf** [comment]
Yes, that's the so-called "Mikesy Glitch". It was discovered quite some time ago, and it's now considered a feature rather than a bug :D

**Comment by ANoDE85** [comment]
Oh, I see 😅
I'll close the issue then.
