### ISSUE TITLE
Crash opening croftengine.exe

### ISSUE THREAD

**Issue by SlightPersimmon1** [stohrendorf/CroftEngine#302]
OS: Windows 8.1 (64)
package version: CroftEngine-2.0-win64.exe 

When opening croftengine.exe i get the following error:

![image](https://user-images.githubusercontent.com/65872044/226109391-66687739-72b3-4718-bbc6-57f14ed4c012.png)

**Comment by stohrendorf** [comment]
There's no support for windows versions earlier than windows 10, sorry. Windows 10 is already nearly 8 years old now.

**Comment by SlightPersimmon1** [comment]
Thanks for the quick reply.
 
Fair enough. But you should be clearer about the system requirements, don't you think?
There are reasons why people still use a pre-windows 10 OS. Privacy reasons, for once. 

It's a pitty. It's the first time i'm using an open source game engine that does not work on my OS. An i use them a lot. From CorsixTH, to KeeperFX, to OpenRA, Augustus, gzdoom, raze, Dune Legacy, exult, FreespaceOpen, and so on.
