### ISSUE TITLE
I can't use Glidos texture pack

### ISSUE THREAD

**Issue by PlanetaRob** [stohrendorf/CroftEngine#307]
I have imported game data from an installation with TombATI.

In Configuration, I click "Select Glidos Texture Pack" and choose the folder where the textures are, but when I run the game they don't load.

I have tried putting the folder in different locations but nothing.

I'm testing with textures from https://www.tombraiderxtra.com/

**Comment by stohrendorf** [comment]
Make sure you extracted the texture pack in a non-protected folder, for example your documents or downloads folder. The desktop or the program files folders are considered protected by windows, and CE respects that, so it won't work if you place it there.

**Comment by PlanetaRob** [comment]
> Make sure you extracted the texture pack in a non-protected folder, for example your documents or downloads folder. The desktop or the program files folders are considered protected by windows, and CE respects that, so it won't work if you place it there.

I have already tried it in several folders: Documents, Downloads, directly in C: and D: (another hd), in the CroftEngine folder (is in D:/Games/CroftEngine)... and I get nothing.
HD textures don't work for me in any folder :(

**Comment by stohrendorf** [comment]
Do you have a `equiv.txt` texture pack (that file should be somewhere in the extracted directories) or one with only folders and images?

**Comment by PlanetaRob** [comment]
It is a folder with images. I'm testing with the ones I use with TombATI.
For example, this one from the Glidos site: http://download.glidos.net/TombATI/TombATI_HD_Textures_v1.0.exe

**Comment by stohrendorf** [comment]
Ah, these can be tricky. For some reason, some people have to configure/select the folder that contains the texture folders *twice*. But just to double check, can you send me your most recent log file where the configuration failed?

**Comment by PlanetaRob** [comment]
Of course! Thank you for your help!
[croftengine.1.log](https://github.com/stohrendorf/CroftEngine/files/11904712/croftengine.1.log)

**Comment by stohrendorf** [comment]
Okay, this is a dumb bug - the engine caches the textures even when loading a texture pack failed. This means that the engine loads the original textures if your first configuration failed:
`Loading cache texture "C:\\Users\\bobno\\AppData\\Local\\croftengine\\texturecache\\tr1\\C27510FC199A46397DB4B4648E5B4C30\\LEVEL1.PHD\\0.pvr"`

The only thing you can do is to manually delete the texture cache when trying to reconfigure the texture pack. Sorry.

**Comment by PlanetaRob** [comment]
> Okay, this is a dumb bug - the engine caches the textures even when loading a texture pack failed. This means that the engine loads the original textures if your first configuration failed: `Loading cache texture "C:\\Users\\bobno\\AppData\\Local\\croftengine\\texturecache\\tr1\\C27510FC199A46397DB4B4648E5B4C30\\LEVEL1.PHD\\0.pvr"`
> 
> The only thing you can do is to manually delete the texture cache when trying to reconfigure the texture pack. Sorry.

I've tried it but it doesn't work either. I don't know if it's a problem with my computer or that those texture packs are not compatible. I've tried three different texture packs and nothing :(

Could you try the one I listed above to find out if it's definitely my team? I will also try to test it on another PC.

**Comment by stohrendorf** [comment]
Ah, you picked an unsupported format, try this one instead: https://download.glidos.net/TR%20Texture%20packs/TR1HD_v1.1.exe

**Comment by PlanetaRob** [comment]
> Ah, you picked an unsupported format, try this one instead: https://download.glidos.net/TR%20Texture%20packs/TR1HD_v1.1.exe

Amazing! Works! Thank yhou so much!

**Comment by stohrendorf** [comment]
No problem.
